### ISSUE TITLE
There are redundant (incorrect) Tagsets originated from the SchemaEngineering sheet.

### ISSUE THREAD

**Issue by jbkoh** [BuildSysUniformMetadata/Brick#10]
original report: https://groups.google.com/d/msgid/brickschema/6374bdb9-d696-443b-9591-346422368f9b%40googlegroups.com?utm_medium=email&utm_source=footer

Example: There are SolarPanel and Solar_Panel
Tagsets should be separated by tags in it. SolarPanel comes from "isPartOf" column, which should be fixed. There are a few more Tagsets like that. Another example is ThermalEnergyStorage.

**Comment by berkoben** [comment]
Another potential Example is Water System / WaterSystem

**Comment by gtfierro** [comment]
What do you mean by "Tagsets should be separated by tags in it"? Is the issue that there are multiple TagSets with the same name? Or some Tags have the same name as TagSets? Or that some TagSets have aliases?

**Comment by jbkoh** [comment]
I meant "TagSets should be able to be separated into Tags". It could be my language problem, but in case it wasn't, I put my logic: 
Tagsets should consist of multiple reusable Tags with unit information though we don't strictly define what unit information is. For example, in the current Tags.csv, there are WaterSystem, LightingSystem, etc. They should be separated into Water System and Lighting System so that anyone knows that they are a kind of System. Otherwise there is no meaning to use Tags.

- There can be multiple Tags with the same name, but I am against TagSets with the same name because users directly use TagSet to represent an entity. And I haven't seen an example for this.
- There can be TagSets that have the same name as Tags (E.g., Elevator as a Tag and Elevator as a TagSet)
- TagSets can have aliases with explicit relationship (owl:sameAs) when they cover different expression. I don't see any usage of keeping SolarPanel and Solar Panel.

**Comment by jbkoh** [comment]
I also see that somebody put ExhaustFan, ReturnFan as Tags intentionally. I would like to understand the reason why he/she put them as Tags even though we have Exhaust, Return, and Fans as Tags already. Any idea?

**Comment by jbkoh** [comment]
done. https://github.com/BuildSysUniformMetadata/Brick/commit/0422abf6cb7cac02c1ee41e8e9c5462d62a7363e
