### ISSUE TITLE
Removing proprietary names

### ISSUE THREAD

**Issue by jbkoh** [BuildSysUniformMetadata/Brick#11]
E.g., EconCycle.
Are we supposed to include proprietary names?

**Comment by gtfierro** [comment]
I feel this is ok, given that its a subclass of something more generic

**Comment by jbkoh** [comment]
It was originally observed at EBU3B UCSD like ``CRAC_EconCycle_On_Off_Status``. It's even not even Equipment. We do not know what EconCycle means for now, so I will leave it until we clarify what it is. Please open this again if anyone would like to clarify this issue.
