### ISSUE TITLE
Missing TagSets.

### ISSUE THREAD

**Issue by jbkoh** [BuildSysUniformMetadata/Brick#12]
I'd like to keep this thread to add missing TagSets whenever it's found. Anybody can add more TagSets here or comments about the list.

- [x] Reheat Coil
- [ ] ~~Pump Flow Status~~
- [x] Chilled Water Pump Alarm
- [x] Fire Alarm
- [ ] ~~Supply Air Volume Sensor~~

EDIT: defer the two points until clarifying the meanings from ``Pump Status`` and ``Flow Sensor``. Not handling those in this issue.

**Comment by gtfierro** [comment]
- [ ] intermediate subclasses for Heating/Cooling Temperature Setpoint
- [ ] Radiators

**Comment by jpsctc** [comment]
- [ ] Combined Heat Power (CHP)
- [ ] Thermal Store
- [ ] Radiators

**Comment by jbkoh** [comment]
@jpsctc Could you provide more details about CHP and Thermal Store? What are the superclasses of them?

@gtfierro @jpsctc Does ``Radiator`` as a ``Terminal Unit`` sound okay? Or right under ``HVAC``?

**Comment by gtfierro** [comment]
`Radiator` can be a subclass of `Terminal Unit`

**Comment by jbkoh** [comment]
Resolved by https://github.com/BuildSysUniformMetadata/Brick/pull/42
