### ISSUE TITLE
RFC: Proposal for RFCs for Brick

### ISSUE THREAD

**Issue by gtfierro** [BuildSysUniformMetadata/Brick#25]
What is the formal plan and process for continuing development on Brick?

## Components
- RFCs: proposals for how to extend Brick. This is where the majority of discussion should take place
- Pull Requests: implemented extensions to Brick. These can be of several different types:
    - Implementation of an approved RFC: discussion should focus on the implementation, should involve extensive testing
    - Bug Fixes: typos, misspellings, inconsistencies: expected minimal discussion
- Versioning:
    - I recommend that Brick stick to [Semver](http://semver.org/):
        Given a version number MAJOR.MINOR.PATCH, increment the:
        - MAJOR version when you make incompatible API changes,
        - MINOR version when you add functionality in a backwards-compatible manner, and
        - PATCH version when you make backwards-compatible bug fixes.
        - Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
- Debugging help/questions: how people learn how to use Brick and we help with any issues they have

### Realization

- RFCs:
    - an RFC will be an issue on GitHub with the "RFC" label. The first post will be the operating RFC document, and discussion will take place in the comments below
    - New RFCs will be announced by a Project Maintainer on the Brick mailing lists, but discussion should be relegated to GitHub
    - RFCs will get the ACCEPTED or REJECTED GitHub label after discussion has concluded; adding this label and concluding the discussion is the responsibility of a Project Maintainer
    - if the RFC involves a change to the Brick ontology, a project maintainer will make a judgement about which release of Brick the implementation will target (see Versioning)
- Pull Requests:
    - Upon the acceptance of an RFC, one or more developers will be assigned to implement the RFC
    - If the RFC is an extension of Brick, then the Pull Request should include:
        - editing the Brick generation src to produce the new Brick file
        - a pointer to which release of Brick the PR is targeting (see Versioning)
        - changes to the example building files to make them compliant with the new version of Brick (if applicable)
        - relevant documentation on how these extensions work and how they are meant to be used
        - ~~TODO: **where does this documentation go?**~~
        - Documentation will go on a "changelist" page on the Brick website
    - If the RFC is a proposal to change the website, alter documentation, or something other than an edit of the Brick ontology, then a
      Pull Request should still be filed on the Brick repository with a pointer to the changes (e.g. if they are on another repo) so that
      discussion can be centralized
- Versioning:
    - If we're not careful, versioning can become an Achilles heel for getting started with Brick, because we've made the choice to place the Brick version in the Brick namespace URI.
        - e.g. https://brickschema.org/schema/1.0.1/Brick#
    - Brick PATCH version numbers should not appear in the namespace URI:
        - e.g. https://brickschema.org/schema/1.0/Brick#
        - PATCHes should not affect how Brick is used, so there is no need to differentiate between them in the URI
        - ~~TODO: **do we even want to use PATCH version numbers?**~~
        - We will keep PATCH numbers; a PATCH number will be assigned to a PR once it is accepted. This solves the problem of having multiple PRs open simultaneously.
    - Brick MINOR version numbers are incremented as the result of a milestone:
        - a milestone is a set of TODO items decided upon by an RFC
        - when all of the TODO items for a milestone are complete, the MINOR version is considered finished
        - this is the most common way of incrementing Brick version numbers
    - a Brick MAJOR version number (e.g. "Brick 2.0") will involve a fundamental, backwards-incompatible change in how Brick is used. 
      I don't anticipate we'll see this anytime soon.
    - put another way, pull requests and RFCs do not automatically result in a MINOR version number increase. Instead, we will decide 
      upon some set of features that constitute a new MINOR version, which will be implemented by a set of pull requests, and then we will do 
      a release of that MINOR version once all of those are done.

**Comment by bbalaji-ucsd** [comment]
Thank you Gabe for putting together a comprehensive proposal for RFC.

I’m onboard with all of the changes proposed.

For the two TODOs:
- The documentation can go on the Brick website, in a separate page called
Change Log (or a similar name)
- I think Patch numbers are still useful to have. The developers working on
these detailed bugs know which version they are working on. However, I
support your suggestion that it doesn’t have to affect the Brick schema
URL. The patch number can be included as a property of the “Brick” class in
the TTL file. We can also add additional details such as last update date
in the properties of Brick class.

Comment:
There may be several different RFCs happening in parallel (e.g. electrical
and water domains). Since they map the versioning sequentially, the
specific version numbers that these RFCs correspond to may be hard to
decide beforehand.

Regards,
Bharath

**Comment by jbkoh** [comment]
I agree on the currently proposed opinions.

One comment that haven't discussed: 
I see that an RFC is directed by a manager to a version but it is unclear when we should decide a version is ready to be released. I still think a quarterly (or half a year) board meeting will help to decide release versions. It'd better separating out version release and version development like schema.org (http://schema.org/docs/about.html#cgsg). (version development = community group, version release = steering group in schema.org terms.) 

In case our group is too small for the separation, a (MAJOR/MINOR) version release can be another RFC that requires discussions/agreements.

**Comment by gtfierro** [comment]
I've updated the RFC to include comments about the PATCH numbers (assigned when the PR is merged) and documentation (ChangeLog page on the Brick site)

In terms of how we decide what comprises a minor version, I think we can play it by ear. Someone can have an RFC with a list of proposed changes, and then this gets saved into a GitHub milestone after its accepted. We then use the milestone to track progress. As an example, I can put together an RFC for Brick 1.1

**Comment by gtfierro** [comment]
Might as well change this to accepted :)
