### ISSUE TITLE
Remove structures of tags.

### ISSUE THREAD

**Issue by jbkoh** [BuildSysUniformMetadata/Brick#3]

**Comment by gtfierro** [comment]
Can you either expand on what this means or close the issue?

**Comment by jbkoh** [comment]
https://github.com/BuildSysUniformMetadata/Brick/commit/4c78d21e1e7882e62089f8e92e275a5476e79d7b seems establishing this issue. Let me ping Joern for this.

**Comment by jpsctc** [comment]
I moved Tags to the BrickTag ontology and changed the dependency hierarchy from BrickFrame>BrickTag>Brick to BrickFrame>Brick>BrickTag. Brick itself does not depend on the Tags anymore in  https://github.com/BuildSysUniformMetadata/Brick/commit/4c78d21e1e7882e62089f8e92e275a5476e79d7b, but, is still fully available in BrickTag.
