### ISSUE TITLE
Removing inverse relationships?

### ISSUE THREAD

**Issue by jbkoh** [BuildSysUniformMetadata/Brick#31]
All,

I felt I needed to bring up this issue while reviewing our paper.

Do we really need inverse relationships? I think it carries more complexity than its convenience. Because every line of a query should be duplicated and united due to allowing inverse relationships. E.g., If I want to find sensors in a room, it should be
```sparql
select ?sensor where {
?sensor bf:hasLocation ex:RM-101 .
UNION
ex:RM-101 bf:isLocationOf ?sensor .
}
```
because a query designer does not know whether a building manager used hasLocation of isLocationOf for the location information. Basically all queries we have used did not consider inverse relationships.

Aslak gave me an interesting example like this to show usage of inverse relationships:
```sparql
select ?room where {
?room hasLocation/isLocationOf ex:RM-101 .
}
```
It is finding rooms located at the same hierarchy (i.e., same floor) of RM-101. However, it also needs to be duplicated and united.
```sparql
select ?room where {
?room hasLocation/isLocationOf ex:RM-101 .
UNION
ex:RM-101 hasLocation/isLocationOf ?room .
}
```

Thoughts?

**Comment by gtfierro** [comment]
Inverse relationships are vital to the usability of Brick. The whole point is it allows you to remove the annoyances above.

In HodDB, 

```sparql
?room hasLocation ex:RM-101 .
```

returns the same results as

```sparql
ex:RM-101 isLocationof ?room
```
If the SPARQL engine you're using doesn't support that part of the OWL ontology, which helps define the inverse edges, then you need to get a better one.

---

As an aside, concatenating the edges `hasLocation` and `isLocationOf` doesn't make any sense to me. Why would we need to do this?

**Comment by jbkoh** [comment]
OK. If a SPARQL engine can recognize it, it should be fine.

The concatenation just reduces two lines of query to a line.
```
?room hasLocation ?floor
ex:RM-101 hasLocation ?floor
```
to
```
?room hasLocation/isLocationOf ex:RM-101
```

I am closing this issue as a SPARQL engine can abstract it.

**Comment by jbkoh** [comment]
I actually reopen it. @gtfierro, I haven't checked it yet, but is it SPARQL standard behavior or your optimization? I think it is an inference stage that is not included in SPARQL standard?

**Comment by gtfierro** [comment]
SPARQL just defines the language, not the semantics or the inference, so I'm not sure what you mean.

Isn't inference the **whole point** we're using RDF/SPARQL?

**Comment by jbkoh** [comment]
SPARQL does not define its implementation but defines the language and its semantics. In other words, if a user sends a query, no matter engine he/she uses, the user expects to receive the same result. I wondered the inferred result is expected in any other SPARQL engines (maybe. but I can't find that specification). The inference is I believe not the part of SPARQL engine but reasoner's. So one can add triples from existing triples using a reasoner but SPARQL engines can be agnostic to it. 

I know it is convenient for a SPARQL engine to handle it, which is a good optimization of HodDB, but wondered if it is standardized (i.e., can any other SPARQL engines produce the same result?).

**Comment by jbkoh** [comment]
Agree that we don't need to remove this feature. Closing this.
