### ISSUE TITLE
RFC: Definition of High-level TagSets of Points.

### ISSUE THREAD

**Issue by jbkoh** [BuildSysUniformMetadata/Brick#34]
Based on the discussion at: https://github.com/BuildSysUniformMetadata/Brick/issues/32

### Motivation
There were no clear definitions of below highlevel Point TagSets.

### Add definitions to following TagSets
1. **Status**: State, position, or condition of an item. (adopted from ASHRAE dictionary) Technically, this value should not be arbitrarily written by users or other systems as it is an observation.
2. **Alarm**: Signal, either audible or visual, or both, that alerts an operator to an off-normal condition which requires some form of corrective action. (adopted from ASHRAE dictionary)
3. **Setpoint**: Point at which the desired property is set. (modified from ASHRAE dictionary)
4. **Sensor**: device or instrument designed to detect and measure a variable.
5. **Command**: output point that determines equipment's behavior directly and/or affects relevant operational points.

### Move Meter to Equipment
Reasoning: Meter's meaning as Point is same as Sensor. We also need the concept of Equipment measuring multiple types of values. Meter can present such things as Equipment having multiple Sensors.

**Comment by jbkoh** [comment]
I am adding the abvoe definitions but the Meter issue is more complicated than I expected as there are many dependent Points named as Meter already. I would like to make the below changes.

1. Change ``Meter, Water Meter, and Steam Meter`` as ``Equipment``. Those are measuring *something* related to the target ``Resources``.
    1. Remove ``Energy Meter`` and ``Power Meter``.
    2. Introduce ``Electricity Meter`` instead.

2. Change some meters into sensors: ``Gas Usage Sensor, Power Sensor, Energy Usage Sensor, Peak Energy Today Sensor, Hot Water Flow Sensor, Steam Usage Sensor, Thermal Power Sensor``, etc.

**Comment by gtfierro** [comment]
I think `Meter` should be a subclass of `Sensor`. `Meter` implies that the quantity is being measured for some sort of billing or accounting purpose. So I say lets keep those `Meter` names as-is, but make sure that `Meter` is a subclass of `Sensor`.

I like having `Energy Meter` and `Power Meter` because these unambiguously describe what they are measuring, whereas `Electricity Meter` doesn't.

Thoughts?

**Comment by jbkoh** [comment]
I know that we are more used to meters as points because people have used it more than using sensors. There are a few reasons why I would like to make ``Meter`` an ``Equipment``.

- There are devices (we call ``Equipment``) whose purpose is only measuring various types of data. ``Meter`` is the best name for it. 

- Haystack defines Meter as Equipment, which would be an important alignment for the compatibility:
https://project-haystack.org/tag/meter

- Though ``Electrical Power Meter`` is unambiguous, something like ``Gas Meter`` is not, which is the common naming convention in our current Brick. Meter could be self-contained to mean "usage", but we could make it clearer with ``Gas Usage Meter``. In the case, ``Meter``'s meaning is entirely overlapped with ``Sensor``. 

- In my proposal, ``Electricity Meter`` does not measure power or energy, but it's a device containing ``Point``s related to eletricity. I.e., it contains points measuring power or energy. In the case, actual triples would look like:
    ```turtle
    :meter1 a brick:Electricity_Meter .
    :meter1 bf:hasPoint :elec_power_sensor1.
    :meter1 bf:hasPoint :elec_energy_sensor1.
    :elec_power_sensor1 a brick:Electrical_Power_Sensor . # or Electricity_Power_Meter
    :elec_energy_sensor1 a brick:Electrical_Energy_Sensor . # or Electricity_Energy_Meter
    ```

I know this could be counter-intuitive due to the convention of the word, ``Meter``. Certain issues like this are difficult only for us to decide as it's related to the industrial conventions. I would like to get industrial experts on those conventions. ASHRAE would be the best venue to discuss, and I think it's an essential collaboration direction (E.g., will the industrial end users accept these words with the discomfort little enough to embrace?). IMO, You and I alone lack in that expertise currently. I can ask JCI also. 

If you don't agree with this, (and I'd totally understand it), we can defer this decision.

**Comment by gtfierro** [comment]
Thanks for the description! This makes it much clearer what you mean. I'm on board with this change. I think it really improves the consistency of how we describe these types of systems.

I think the push-back we'd get would center on whether or not you describe the piece of equipment separate from the sensors it contains. This crops up in other scenarios (e.g. if you only have "rotation frequency" for a VFD, do you represent the full equipment in the graph or just the point?), but I firmly believe that describing the equipment and points separately is the right way to go.

**Comment by jbkoh** [comment]
resolved by https://github.com/BuildSysUniformMetadata/Brick/pull/42
