### ISSUE TITLE
Is ``Pump_Alarm_Delay_Setpoint `` a subclass of ``Alarm``?

### ISSUE THREAD

**Issue by jbkoh** [BuildSysUniformMetadata/Brick#40]
Was it intentional? There are several points like that:
```
INCORRECT: Low_Humidity_Alarm_Setpoint in Alarm
INCORRECT: CRAC_Low_Humidity_Alarm_Setpoint in Alarm
INCORRECT: Pump_Alarm_Delay_Setpoint in Alarm
INCORRECT: Chilled_Water_Pump_Alarm_Delay_Setpoint in Alarm
INCORRECT: CWS_Chilled_Water_Pump_Alarm_Delay_Setpoint in Alarm
INCORRECT: CRAC_High_Humidity_Alarm_Setpoint in Alarm
INCORRECT: High_Humidity_Alarm_Setpoint in Alarm
INCORRECT: CRAC_Low_Temperature_Alarm_Setpoint in Alarm
INCORRECT: Low_Temperature_Alarm_Setpoint in Alarm
INCORRECT: High_Temperature_Alarm_Setpoint in Alarm
INCORRECT: CRAC_High_Temperature_Alarm_Setpoint in Alarm
```

I will fix this if it wasn't intentional.

**Comment by gtfierro** [comment]
Why shouldnt these be alarms? It seems like they all for that description

**Comment by jbkoh** [comment]
Simply put, ``Alarm`` is a read point and ``Setpoint`` is a write point. 

In my understanding, ``Low Humidity Alarm Setpoint`` is a setpoint, of which value indicates whether an alarm should be set or off. I.e., ``Low Humidity Alarm Setpoint`` is related to ``Alarm`` but it's not a type of ``Alarm``.

**Comment by gtfierro** [comment]
`Alarm Setpoint` is the value at which the alarm triggers, so its a bit of both, but I think I agree that it should be a subclass of `Setpoint` rather than a subclass of `Alarm`

**Comment by jbkoh** [comment]
resolved by https://github.com/BuildSysUniformMetadata/Brick/pull/42
