### ISSUE TITLE
Change Base URI to brickschema.org

### ISSUE THREAD

**Issue by jbkoh** [BuildSysUniformMetadata/Brick#7]

**Comment by gtfierro** [comment]
Addressed by https://github.com/BuildSysUniformMetadata/Brick/pull/9

Acceptance of PR predicated on the example buildings being updated with the new URI

**Comment by jbkoh** [comment]
done: https://github.com/BuildSysUniformMetadata/Brick/commit/6f20dd82dc9d78fb8c3b15f33467f1854cf7f29c
